version: '3.8'

services:
  db:
    container_name: golangproject_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: goproject
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  server:
    container_name: golangproject_server
    build: ./server/
    ports:
      - "9000:9000"
    environment:
      pg_host: "golangproject_postgres"
    depends_on:
      - db
    links:
      - db
    restart: on-failure

volumes:
  pg_data:
